# 环境相关的配置
environment:
    # 环境类型
    type: "Torcs"

# 折扣因子
gamma: 0.99
# GAE参数
lamda: 0.95
# 更新次数
updates: 39062
# 训练周期
epochs: 3
# 工作进程数
n_workers: 1
# 工作步长
worker_steps: 256
# 小批量数
n_mini_batch: 16
# 值损失系数
value_loss_coefficient: 0.25
# 隐藏层大小
hidden_layer_size: 512
# 最大梯度范数
max_grad_norm: 0.5
# 保存间隔
save_interval: 40

# 循环神经网络配置
recurrence:
    # 序列长度
    sequence_length: 8
    # 隐藏状态大小
    hidden_state_size: 256
    # 层类型
    layer_type: lstm
    # 是否重置隐藏状态
    reset_hidden_state: False

# 学习率调度配置
learning_rate_schedule:
    # 初始学习率
    initial: 5e-4
    # 最终学习率
    final: 5e-4
    # 衰减方式
    power: 1.0
    # 最大衰减步数
    max_decay_steps: 300

# beta调度配置
beta_schedule:
    # 初始beta
    initial: 0.001
    # 最终beta
    final: 0.001
    # 衰减方式
    power: 1.0
    # 最大衰减步数
    max_decay_steps: 300

# 裁剪范围调度配置
clip_range_schedule:
    # 初始裁剪范围
    initial: 0.2
    # 最终裁剪范围
    final: 0.2
    # 衰减方式
    power: 1.0
    # 最大衰减步数
    max_decay_steps: 300
